theme = "hugo-theme-codex"
baseURL = "https://brendangriffen.com/"
languageCode = "en-us"
title = "Brendan Griffen"
copyright = "© {year} Brendan Griffen"

[params]
  twitter = "https://twitter.com/bgriffen"
  github = "https://github.com/bgriffen"
  email = "mailto:brendan.f.griffen@gmail.com"
  iconOrder = ["GitHub", "Email", "Twitter"]
  Description = "Brendan Griffen is a computational astrophysicist by training working at intersection of computer science and biotechnology. Currently, CTO & co-founder of Dynomics."
  customCss = ["css/custom.css"]

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "home"
  name = " home"
  title = "Home"
  url = "/"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/posts"

[[menu.main]]
  identifier = "cv"
  name = "cv"
  title = "CV"
  url = "https://github.com/bgriffen/cv"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
