# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://brendangriffen.com/"
title: bfg
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: about
          url: about/
          weight: 1
        - name: code
          url: code/
          weight: 2
        - name: blog
          url: posts/
          weight: 3
        #- name: archive
        #  url: archives
        #  weight: 4
        #- name: Search
        #  url: search/
        #  weight: 10
        #- name: Tags
        #  url: tags/
        #  weight: 10
        - name: papers
          url: https://scholar.google.com.au/citations?user=ndwtPccAAAAJ
          weight: 4
        #- name: cv
        #  url: https://github.com/bgriffen/cv/


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "An ex-astrophysicist building the future of biotech."
  author: Brendan Griffen
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  #images: ["images/papermod-cover.png"]
  math: true
  projectcards:
    - title: "imcyt"
      image: "assets/imcyt.jpg"
      description: "All-in-one cell-based assay platform that applies ML models to single cell cytometry data and calculates yields and cost model for a given protocol (e.g. cost per unit of dopaminergic neurons or cost per unit of cultured meat). Think of it as a recipe engine for optimised cell based processes."
      url: "https://github.com/bgriffen/gigpy"
      topic: "biotech"
      tags: ["python", "SQL", "machine learning"]
    - title: "wombat"
      image: "assets/wombat.jpg"
      description: "Wombat is a Python toolkit designed help answer geospatial related questions about Australian cities & regions. A simple to use set of functionalities enable the querying of of a large number of open-source datasets simultaneously. These datasets range from aerial imagery, building morphology, census information (e.g. demographics), points of interest, elevation, flooding, education, property sale history and transport networks. The goal of Wombat is to make it a good means to an ends, such that data products can be easily fed into other downstream geospatial analyses and visualisations."
      url: "https://wombat.grifflabs.dev"
      topic: "geospatial"
      tags: ["geospatial", "python"]
    - title: "specufestor"
      image: "assets/specufestor.jpg"
      description: "Specufestor is a Python package designed to streamline the acquisition and analysis of Australian property sale data. This tool collects and organizes historical property sales data, and utilises various property attributes including photos and geospatial datasets sourced through Wombat. Specufestor not only aggregates extensive property data but also employs predictive models to forecast property prices. It was primarily designed to find somewhere to live in the midst of a housing crisis but was subsequently expanded to be more useful."
      url: "https://github.com/bgriffen/specufestor"
      topic: "geospatial"
      tags: ["geospatial","python","machine learning"]
    - title: "the caterpillar project"
      image: "assets/caterpillar.jpg"
      description: "The Caterpillar Project is a large suite of dark matter only cosmological simulations of 35 Milky Way-sized galaxies. At a resolution of ${10^4 M_{\\odot}}$ per particle and 50 Myr temporal resolution, at the time represented one of the largest and highest resolution simulation suites of its kind in the world. These data were generated to help enable statistically probe the formation history and evolution of the Milky Way and its similar sized cousins."
      url: "https://github.com/caterpillarproject/"
      topic: "astro"
      tags: ["python", "numerical", "HPC"]
    - title: "cosmology made easy"
      image: "assets/cme.jpg"
      description: "CME is a 'no-code' Python-based Graphical User Interface (GUI) engineered to manage and execute 'zoom-in' simulations of smaller cosmological regions from larger parent volumes. This constructs Lagrangian volumes and submits subsequent suites to HPC environments, enabling careful checks and optimizations of simulation parameters over an ensemble of runs. Key functionalities include the visualization of dark matter halo catalogues and Lagrangian volumes. CME collectively supports the design and execution of 'optimal' cosmological zoom-in simulations."
      url: "https://github.com/bgriffen/cme"
      topic: "astro"
      tags: ["python","qt", "HPC"]
    - title: "pypump"
      image: "assets/pypump.jpg"
      description: "There is a little public code on handling liquid handlers via serial controllers. PyPump is a Python based tool that uses PySerial to control the [Tricontinent MC6000/C3000](https://www.tricontinent.com/en-au/mc6000-syringe-pump) & [IDEX Rheodyne MX Series II](https://www.idex-hs.com/store/product-detail/mx_series_ii_2_position_6_port_ultralife_switching_valve/mxt715-000) liquid handlers. It is designed to remove the technical work of making GUIs work smoothly with liquid handler operations (e.g. Daedalus). It may only help a few number of people, but it will save them many months should they discover this humble olive branch."
      url: "https://github.com/bgriffen/pypump"
      topic: "hardware"
      tags: ["hardware", "liquid handling", "microfluidics"]
    - title: "daedalus"
      image: "assets/daedalus.jpg"
      description: "A Graphical User Interface in Kivy that executes cloud based (Airtable) liquid handling protocols, in this case feeding liquids to a microfluidic cell-culture circuit at very slow, but contious flow rates over many days. Integrates with pypump to work with the Tricontinent MC6000/C3000 & IDEX Rheodyne MX Series II liquid handlers."
      url: "https://github.com/scaledbiolabs/daedelus"
      topic: "biotech"
      tags: ["biotech", "controller", "GUI", "microfluidics"]
    - title: "protocoldb"
      image: "assets/protocoldb.jpg"
      description: "protocolDB is a Python package designed to streamline the management of laboratory protocols and associated data in a structured database, easily accessible for querying and analysis. It automates database connections and setups, supporting both MySQL and PostgreSQL. Utilizing an ORM, the package defines a comprehensive schema encompassing projects, runs, experiments, samples, imaging, results, and various inventory items like components, cell lines, and media. The tool simplifies data entry and retrieval, enabling researchers to manage complex datasets involving multiple experimental steps, from seeding and medium changes to dissociation and detection instances."
      url: "https://github.com/scaledbiolabs/protocoldb"
      topic: "biotech"
      tags: ["assays", "python", "SQL"]
    - title: "ezpubmed"
      image: "assets/ezpubmed.jpg"
      description: "ezpubmed is a Python package designed to maintain an up-to-date local datastore of the world's biomedical literature (pubmed), easily convertible into a pandas DataFrame for analysis. It automates the synchronization of PubMed's 'baseline' and 'updatefiles' datasets, which include all historical papers and current year entries. Utilizing the peewee ORM, it efficiently manages updates and metadata corrections in a SQLite database. The tool simplifies the setup process and supports advanced functionalities such as custom queries and basic NLP tasks (e.g. LLMs), making it an effective solution for researchers needing streamlined access to comprehensive PubMed data."
      url: "https://github.com/bgriffen/ezpubmed"
      topic: "biotech"
      tags: ["python", "natural language processing"]


  profileMode:
    enabled: false
    title: Hi, I'm Brendan.
    imageUrl: "#"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    subtitle: "Ex-astrophysicist building deep tech platforms."
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi, I'm"
    Name: "Brendan"
    Content: >
      Ex-astrophysicist building deep tech platforms.  

      CTO & co-founder @ [Dynomics Inc](https://dynomics.com).  

  socialIcons:
    - name: github
      url: "https://github.com/bgriffen"
    - name: email
      url: "mailto:contact@grifflabs.dev"
    - name: twitter
      url: "https://www.twitter.com/brendangriffen/"
    - name: linkedin
      url: "https://www.linkedin.com/in/brendangriffen/"
    - name: RsS
      url: "index.xml"

  editPost:
    URL: "https://github.com/bgriffen/brendangriffen.com/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"
  label:
      text: "bfg"
      #icon: icon.png
      iconHeight: 35

  assets:
    disableHLJS: true
    favicon: "favicon.ico"
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
      hidden: true # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  #highlight:
  #  noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
