baseURL: "https://brendangriffen.com"
title: Brendan Griffen
paginate: 20
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about/
                  weight: 1
                - name: Blog
                  url: posts/
                  weight: 2
                #- name: Tags
                #  url: tags
                #  weight: 3
                #- name: Categories
                #  url: categories
                #  weight: 4
                #- name: Series
                #  url: series
                  weight: 5
                - name: Archive
                  url: archives/
                  weight: 6
        #buttons:
        #    - name: Blog
        #      url: posts
        #    - name: Tags
        #      url: tags
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "An ex-astrophysicist building the future of biotech."
    author: Brendan Griffen
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    #images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Hi, I'm Brendan.
        #imageUrl: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTc5ODc5NjY5ODU0NjQzMzIy/gettyimages-3091504.jpg"
        #imageTitle: my image
        imageWidth: 150
        imageHeight: 150
        subtitle: "Ex-astrophysicist building the future of biotech."
        #buttons:
        #    - name: Blog
        #      url: posts
        #    - name: Tags
        #      url: tags

    homeInfoParams:
        Title: "Hi, I'm"
        Name: "Brendan"
        Content: >
            Ex-astrophysicist building the future of biotech.
             - CTO & co-founder @ [Dynomics Inc](https://dynomics.com).

    socialIcons:
        - name: github
          url: "https://github.com/bgriffen"
        - name: email
          url: "mailto:brendan.f.griffen@gmail.com"
        - name: twitter
          url: "https://www.twitter.com/brendangriffen/"
        - name: linkedin
          url: "https://www.linkedin.com/in/brendangriffen/"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/bgriffen/website/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
        text: "bfg"
        #icon: icon.png
        iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    #assets:
    #    favicon: "/favicon.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
